[geany]
pref_main_load_session=true
pref_main_project_file_in_basedir=true
pref_main_save_winpos=true
pref_main_save_wingeom=true
pref_main_confirm_exit=false
pref_main_suppress_status_messages=false
switch_msgwin_pages=false
beep_on_errors=true
auto_focus=false
sidebar_symbol_visible=true
sidebar_openfiles_visible=true
editor_font= 	ç-V
tagbar_font= “Cç-V
msgwin_font= “Cç-V
show_notebook_tabs=true
show_tab_cross=true
tab_order_ltr=true
tab_order_beside=false
tab_pos_editor=2
tab_pos_msgwin=0
tab_label_length=1000
use_native_dialogs=false
show_indent_guide=false
show_white_space=false
show_line_endings=false
show_line_endings_only_when_differ=false
show_markers_margin=true
show_linenumber_margin=true
long_line_enabled=true
long_line_type=0
long_line_column=72
long_line_color= “Cç-V
symbolcompletion_max_height=10
symbolcompletion_min_chars=4
use_folding=true
unfold_all_children=false
use_indicators=true
line_wrapping=false
auto_close_xml_tags=true
complete_snippets=true
auto_complete_symbols=true
pref_editor_disable_dnd=false
pref_editor_smart_home_key=true
pref_editor_newline_strip=false
line_break_column=72
auto_continue_multiline=true
comment_toggle_mark= “Cç-V
scroll_stop_at_last_line=true
autoclose_chars=0
pref_editor_default_new_encoding=UTF-8
pref_editor_default_open_encoding=none
default_eol_character=2
pref_editor_new_line=true
pref_editor_ensure_convert_line_endings=false
pref_editor_replace_tabs=false
pref_editor_trail_space=false
pref_toolbar_show=true
pref_toolbar_append_to_menu=false
pref_toolbar_use_gtk_default_style=true
pref_toolbar_use_gtk_default_icon=true
pref_toolbar_icon_style=0
pref_toolbar_icon_size=0
pref_template_developer=€HMç-V
pref_template_company=€HMç-V
pref_template_mail=0şiç-V
pref_template_initial=àHMç-V
pref_template_version=àHMç-V
pref_template_year=%Y
pref_template_date=%Y-%m-%d
pref_template_datetime=%d.%m.%Y %H:%M:%S %Z
context_action_cmd=0ãH\rñ
menubar_visible=true
sidebar_visible=true
statusbar_visible=true
msgwindow_visible=false
fullscreen=false
symbols_group_by_type=true
color_picker_palette=ğ3…ç-V
scribble_text=
scribble_pos=0
custom_date_format=Ô’…(V

[tools]
terminal_cmd=
browser_cmd=Q
grep_cmd=\s\tÄæ-V

[printing]
print_cmd_common_format=ô=“…(V
use_gtk_printing=true
print_line_numbers=true
print_page_numbers=true
print_page_header=true
page_header_basename=false
page_header_datefmt=ğWÉç-V

[VTE]
load_vte=true
font=
scroll_on_key=true
scroll_on_out=true
enable_bash_keys=true
ignore_menu_bar_accel=false
follow_path=false
run_in_vte=false
skip_run_script=false
cursor_blinks=false
scrollback_lines=500
shell=È…(V
colour_fore=#FFFFFF
colour_back=#000000
