[files]
recent_files=
recent_projects=
current_page=-1

[project]
session_file=
project_file_path=/home/mostafa/projects

[geany]
treeview_position=230
msgwindow_position=904
geometry=0;0;1;1;0;

[VTE]
last_dir=\s\n\nç-V
